### ISSUE TITLE
References unused service id

### ISSUE THREAD

**Issue by tpaulshippy** [StrongMind/canvas_shim#363]
com.powerschool.class.dcids is not a thing...
This is the only spot where it exists in code. But there is no such thing as a "class" in PowerSchool. There are courses and sections.

https://github.com/StrongMind/canvas_shim/blob/09bf1e441f06ac0ecd0f2af94cb7267c93f7d06a/app/services/identifier_mapper_service/client.rb#L40

**Comment by YupItsZac** [comment]
This is also unused code. That service did exist for a minute, but no longer does. We get this from our settings service now.
